export const INJECTABLE_METADATA_KEY = Symbol('INJECTABLE_METADATA_KEY');
export const SCOPE_METADATA_KEY = Symbol('SCOPE_METADATA_KEY');
export const INJECT_METADATA_KEY = Symbol('INJECT_METADATA_KEY');
